version: '3.0'

expectations:
  population_size: 10000

actions:


  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        dates: analysis/lib/dates.json
        groups: analysis/lib/diagnosis_groups.json
        lookup: analysis/lib/diagnosis_groups_lookup.rds
        labels: analysis/lib/variable_labels.rds


  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    # dummy_data_file: -- not yet in use because of https://github.com/opensafely-core/cohort-extractor/issues/611#issuecomment-893544024
    needs: [design]
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  process:
    run: r:latest analysis/process.R
    needs: [design, extract]
    outputs:
      highly_sensitive:
        cohort: output/data/data_cohort.rds

  descr_table1:
    run: r:latest analysis/table1.R
    needs: [design, process]
    outputs:
      highly_sensitive:
        rds: output/table1/*.rds
      moderately_sensitive:
        html: output/table1/*.html
        csv: output/table1/*.csv

  descr_vaxdate:
    run: r:latest analysis/vax_date.R
    needs: [design, process]
    outputs:
      highly_sensitive:
        rds: output/vaxdate/*.rds
      moderately_sensitive:
        png: output/vaxdate/*.png

  descr_diagnoses:
    run: r:latest analysis/diagnoses.R
    needs: [design, process]
    outputs:
      moderately_sensitive:
        png: output/diagnoses/*.png


  rmd_report:
    run: r:latest -e 'rmarkdown::render("analysis/report.Rmd",  knit_root_dir
      = "/workspace",  output_dir = "/workspace/output/report"   )'
    needs: [design, descr_table1, descr_vaxdate, descr_diagnoses]
    outputs:
      moderately_sensitive:
        html: output/report/report.html
        md: output/report/report.md
        figures: output/report/figures/*.png
