version: '3.0'

expectations:
  population_size: 10000

actions:


  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    # dummy_data_file: -- not yet in use because of https://github.com/opensafely-core/cohort-extractor/issues/611#issuecomment-893544024
    outputs:
      highly_sensitive:
        cohort: output/input.feather
    outputs:
      highly_sensitive:
        cohort: output/input.csv
